- type: playTimeTracker
  id: FWJobKing

- type: playTimeTracker
  id: FWJobGuardCaptain

- type: playTimeTracker
  id: FWJobGuard

- type: playTimeTracker
  id: FWJobBlacksmith

- type: playTimeTracker
  id: FWJobPeasant
